name: Build Forge Mod

  on:
    push:
      branches: [ main ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: temurin

        - name: Build with Gradle
          run: ./gradlew build

        - name: Upload JAR as artifact
          uses: actions/upload-artifact@v3
          with:
            name: mod-jar
            path: build/libs/*.jar
